/**
 * One-off: for matches that have henrik_id + rounds + opp_players but
 * ZERO match_players rows (silent failure during original import),
 * re-fetch Henrik and emit INSERT statements for the 5 ourPlayers.
 *
 * Usage:
 *   npx tsx scripts/backfill-missing-match-players.mts <input-json>
 *
 * Input JSON: [{ id, henrik_id, team_slug, match_id_helldock }, ...]
 * Output:     scripts/_out/missing-mp-insert.sql
 *
 * Resolves player_id via player_accounts (puuid first, then riot_id),
 * leaves player_id NULL for unknown accounts — user can link via UI.
 */
import { writeFileSync, mkdirSync, readFileSync } from 'node:fs'
import { fetchMatchByIdV4, isPremierMatch } from '../src/lib/henrik/client'
import { transformMatchToRows, type OurPlayerData } from '../src/lib/henrik/transformers'
import { TEAM_CONFIGS } from '../src/lib/teams'

const API_KEY = process.env.HENRIK_API_KEY ?? ''
if (!API_KEY) {
  console.error('HENRIK_API_KEY env var required')
  process.exit(1)
}

type MatchInput = {
  id: string
  henrik_id: string
  team_slug: string
  match_id_helldock: string
}

function s(value: string | null): string {
  if (value === null) return 'NULL'
  return `'${value.replace(/'/g, "''")}'`
}
function n(value: number | null | undefined): string {
  return value === null || value === undefined ? 'NULL' : String(value)
}

async function main() {
  const inputPath = process.argv[2]
  if (!inputPath) {
    console.error('Usage: tsx scripts/backfill-missing-match-players.mts <input-json>')
    process.exit(1)
  }
  const matches = JSON.parse(readFileSync(inputPath, 'utf8')) as MatchInput[]
  mkdirSync('scripts/_out', { recursive: true })

  const sqlLines: string[] = []
  sqlLines.push('-- Auto-generated by backfill-missing-match-players.mts')
  sqlLines.push('-- INSERTs match_players rows for matches that imported partially.')
  sqlLines.push('-- player_id resolved from player_accounts; NULL when unknown (user links via UI).')
  sqlLines.push('BEGIN;')

  for (let i = 0; i < matches.length; i++) {
    const m = matches[i]
    process.stderr.write(`[${i + 1}/${matches.length}] ${m.match_id_helldock} (${m.team_slug})... `)
    if (i > 0) await new Promise((r) => setTimeout(r, 1500))

    const cfg = TEAM_CONFIGS[m.team_slug]
    if (!cfg) {
      process.stderr.write('SKIP (no team config)\n')
      continue
    }

    const raw = await fetchMatchByIdV4(m.henrik_id, cfg.mainAccount.region, API_KEY)
    if (!raw || raw?.errors) {
      process.stderr.write(`HENRIK ERR\n`)
      continue
    }
    const mainRiotId = `${cfg.mainAccount.name}#${cfg.mainAccount.tag}`
    const xf = transformMatchToRows(raw, mainRiotId, cfg.roster, isPremierMatch(raw))
    if ('error' in xf) {
      process.stderr.write(`XF ERR: ${xf.error}\n`)
      continue
    }

    sqlLines.push(`-- ${m.match_id_helldock} — inserting ${xf.ourPlayers.length} match_players rows`)
    for (const p of xf.ourPlayers as OurPlayerData[]) {
      const cols = [
        'match_id', 'agent', 'role', 'k', 'd', 'a', 'acs', 'plus_minus',
        'plants', 'defuses', 'fk', 'fd', 'two_k', 'three_k', 'four_k', 'aces',
        'clutches', 'clutch_1v2plus', 'hs', 'bs', 'ls', 'damage_made', 'damage_received',
        'adr', 'ability_c', 'ability_q', 'ability_e', 'ability_x', 'rounds_afk',
        'friendly_fire_outgoing', 'friendly_fire_incoming',
        'riot_name', 'riot_tag', 'puuid',
        'player_id',
      ]
      // player_id resolved at apply-time via subquery against player_accounts.
      const playerIdExpr = p.puuid
        ? `(SELECT player_id FROM player_accounts WHERE puuid = ${s(p.puuid)} LIMIT 1)`
        : `(SELECT player_id FROM player_accounts WHERE riot_name = ${s(p.riot_name)} AND riot_tag = ${s(p.riot_tag)} LIMIT 1)`

      const values = [
        s(m.id),
        s(p.agent), s(p.role),
        n(p.k), n(p.d), n(p.a), n(p.acs), n(p.plus_minus),
        n(p.plants), n(p.defuses), n(p.fk), n(p.fd),
        n(p.two_k), n(p.three_k), n(p.four_k), n(p.aces),
        n(p.clutches), n(p.clutch_1v2plus),
        n(p.hs), n(p.bs), n(p.ls),
        n(p.damage_made), n(p.damage_received), n(p.adr),
        n(p.ability_c), n(p.ability_q), n(p.ability_e), n(p.ability_x),
        n(p.rounds_afk),
        n(p.friendly_fire_outgoing), n(p.friendly_fire_incoming),
        s(p.riot_name), s(p.riot_tag), p.puuid ? s(p.puuid) : 'NULL',
        playerIdExpr,
      ]

      sqlLines.push(
        `INSERT INTO match_players (${cols.join(', ')}) VALUES (${values.join(', ')});`
      )
    }
    process.stderr.write(`OK\n`)
  }

  sqlLines.push('COMMIT;')
  const outPath = 'scripts/_out/missing-mp-insert.sql'
  writeFileSync(outPath, sqlLines.join('\n') + '\n')
  process.stderr.write(`\nWrote → ${outPath}\n`)
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
