/**
 * One-off: re-fetches Henrik V4 match payloads for matches that have
 * orphaned match_players (player_id IS NULL with no riot_name) and writes
 * UPDATE statements that backfill riot_name / riot_tag / puuid on those
 * rows. Identifies each row by (match_id, agent, k, d, a) which is
 * effectively unique within a single match.
 *
 * Usage: npx tsx scripts/backfill-orphan-riot-ids.mts <orphan-matches.json>
 *
 * Input JSON shape: [{ id, henrik_id, team_slug, match_id_helldock }, ...]
 * Output: scripts/_out/orphan-backfill.sql
 *
 * Does NOT set player_id — keeps the row orphaned so the user can link it
 * via the /matches/[id] alt-account UI. The point of this script is to
 * populate the riot_name / riot_tag / puuid so the link UI can identify
 * the unknown player.
 */
import { writeFileSync, mkdirSync, readFileSync } from 'node:fs'
import { fetchMatchByIdV4, isPremierMatch } from '../src/lib/henrik/client'
import { transformMatchToRows } from '../src/lib/henrik/transformers'
import { TEAM_CONFIGS } from '../src/lib/teams'

const API_KEY = process.env.HENRIK_API_KEY ?? ''
if (!API_KEY) {
  console.error('HENRIK_API_KEY env var required')
  process.exit(1)
}

type MatchInput = {
  id: string
  henrik_id: string
  team_slug: string
  match_id_helldock: string
}

function sqlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`
}

async function main() {
  const inputPath = process.argv[2]
  if (!inputPath) {
    console.error('Usage: tsx scripts/backfill-orphan-riot-ids.mts <input-json>')
    process.exit(1)
  }
  const matches = JSON.parse(readFileSync(inputPath, 'utf8')) as MatchInput[]

  mkdirSync('scripts/_out', { recursive: true })
  const sqlLines: string[] = []
  sqlLines.push('-- Auto-generated by backfill-orphan-riot-ids.mts')
  sqlLines.push('-- Each UPDATE targets a single orphan row by (match_id, agent, k, d, a).')
  sqlLines.push('-- player_id is intentionally NOT set — user links via UI.')
  sqlLines.push('BEGIN;')

  let total = 0
  for (let i = 0; i < matches.length; i++) {
    const m = matches[i]
    process.stderr.write(`[${i + 1}/${matches.length}] ${m.match_id_helldock} (${m.team_slug})... `)
    if (i > 0) await new Promise((r) => setTimeout(r, 1500)) // throttle

    const cfg = TEAM_CONFIGS[m.team_slug]
    if (!cfg) {
      process.stderr.write('SKIP (no team config)\n')
      continue
    }

    const raw = await fetchMatchByIdV4(m.henrik_id, cfg.mainAccount.region, API_KEY)
    if (!raw || raw?.errors) {
      process.stderr.write(`HENRIK ERR\n`)
      continue
    }

    const mainRiotId = `${cfg.mainAccount.name}#${cfg.mainAccount.tag}`
    const xf = transformMatchToRows(raw, mainRiotId, cfg.roster, isPremierMatch(raw))
    if ('error' in xf) {
      process.stderr.write(`XF ERR: ${xf.error}\n`)
      continue
    }

    sqlLines.push(`-- ${m.match_id_helldock} (${m.team_slug}) — ${xf.ourPlayers.length} ourPlayers`)
    for (const p of xf.ourPlayers) {
      const setParts: string[] = []
      setParts.push(`riot_name = ${sqlString(p.riot_name)}`)
      setParts.push(`riot_tag = ${sqlString(p.riot_tag)}`)
      if (p.puuid) setParts.push(`puuid = ${sqlString(p.puuid)}`)

      sqlLines.push(
        `UPDATE match_players SET ${setParts.join(', ')} ` +
          `WHERE match_id = '${m.id}' ` +
          `AND player_id IS NULL ` +
          `AND riot_name IS NULL ` +
          `AND agent = ${sqlString(p.agent)} ` +
          `AND k = ${p.k} AND d = ${p.d} AND a = ${p.a};`
      )
      total++
    }
    process.stderr.write(`OK (${xf.ourPlayers.length} ourPlayers queued)\n`)
  }

  sqlLines.push('COMMIT;')
  const outPath = 'scripts/_out/orphan-backfill.sql'
  writeFileSync(outPath, sqlLines.join('\n') + '\n')
  process.stderr.write(`\nWrote ${total} UPDATE statements → ${outPath}\n`)
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
